const defaultArms =
  "https://pic.ebid.net/upload_medbig/5/6/4/uo_1596811661-32027-154.jpg";

const defaultImage =
  "https://www.thesprucepets.com/thmb/_yrib2KGkS4VJSgCQEl59KPUPOU=/1885x1414/smart/filters:no_upscale()/GettyImages-135630198-5ba7d225c9e77c0050cff91b.jpg";

const userSeed = [
  {
    mundaneFirstName: "Matt",
    mundaneLastName: "Merkel",
    scaFirstName: "Klaus",
    scaLastName: "",
    registeredName: true,
    registeredArms: true,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield", "spear"],
    gearStatus: true,
    memberStatus: "officer",
    admin: true,
    rank: "Dread Lord",
    image: defaultImage,
    arms: "/deviceImages/KlausArms.jpg",
    notes: '',
    title: 'Sir',
    phoneNumber: '732-710-9597',
    email: 'klausw84@gmail.com',
    address: '215 Sunset Ln, Howell Township, NJ 07731',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Felicia",
    mundaneLastName: "Merkel",
    scaFirstName: "Anastasia",
    scaLastName: "",
    registeredName: false,
    registeredArms: false,
    singlesFighter: false,
    combatArcher: false,
    meleeFighter: false,
    authorizedForms: [],
    gearStatus: false,
    memberStatus: "officer",
    admin: true,
    rank: "Dread Lady",
    image: defaultImage,
    arms: '/deviceImages/StasiaArms.jpg',
    notes: '',
    title: 'Lady',
    phoneNumber: '908-331-1684',
    email: '',
    address: '215 Sunset Ln, Howell Township, NJ 07731',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Tyler",
    mundaneLastName: "Stanley",
    scaFirstName: "Guillaume",
    scaLastName: "Du Chantier",
    registeredName: true,
    registeredArms: true,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield", "spear"],
    gearStatus: true,
    memberStatus: "officer",
    admin: true,
    rank: "Sergeant",
    image: defaultImage,
    arms: "/deviceImages/GuisArms.jpg",
    notes: '',
    title: 'Lord',
    phoneNumber: '856-916-1885',
    email: 'tylerguistanley@gmail.com',
    address: '121 W Tulpehocken, Apt E311, Philadelphia, PA 19144',
    memberId: '',
    authExpirationDate: '',

  },
  {
    mundaneFirstName: "Travis",
    mundaneLastName: "Vaughan",
    scaFirstName: "Lawrence",
    scaLastName: "",
    registeredName: true,
    registeredArms: true,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield", "spear"],
    gearStatus: true,
    memberStatus: "officer",
    admin: true,
    rank: "quartermaster",
    image: defaultImage,
    arms: "/deviceImages/LawrenceArms.jpg",
    notes: '',
    title: 'First Sworn/Lord',
    phoneNumber: '856-524-0308',
    email: 'travisvaughan17@yahoo.com',
    address: '130 Congress Ave, Oaklyn, NJ 08107',
    memberId: '',
    authExpirationDate: '',

  },
  {
    mundaneFirstName: "Victoria",
    mundaneLastName: "Twaites",
    scaFirstName: "Ezra",
    scaLastName: "Di Bazzi",
    registeredName: false,
    registeredArms: true,
    singlesFighter: false,
    combatArcher: false,
    meleeFighter: false,
    authorizedForms: [],
    gearStatus: false,
    memberStatus: "member",
    admin: true,
    rank: "grunt",
    image: defaultImage,
    arms: "/deviceImages/VicsArms.jpg",
    notes: '',
    title: '',
    phoneNumber: '507-412-9503',
    email: 'vtworks.film@gmail.com',
    address: '121 W Tulpehocken, Apt E311, Philadelphia, PA 19144',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Karen",
    mundaneLastName: "MacPherson",
    scaFirstName: "Rhynn",
    scaLastName: "",
    registeredName: true,
    registeredArms: true,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield", "spear"],
    gearStatus: false,
    memberStatus: "member",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '214-868-2420',
    email: 'kam0112@gmail.com',
    address: '4403 Nightfall ct., Durham, NC, 27713',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Brian",
    mundaneLastName: "Payseur",
    scaFirstName: "Gilbert",
    scaLastName: "idk",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: true,
    meleeFighter: true,
    authorizedForms: ["polearm", "combat-archery"],
    gearStatus: false,
    memberStatus: "onwatch",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '732-610-4180',
    email: 'brianpayseur@gmail.com',
    address: '170 Eva ct, Jackson, NJ 08257',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Erica",
    mundaneLastName: "Payseur",
    scaFirstName: "Jeromina",
    scaLastName: "De la Cueva",
    registeredName: false,
    registeredArms: false,
    singlesFighter: false,
    combatArcher: false,
    meleeFighter: false,
    authorizedForms: [],
    gearStatus: false,
    memberStatus: "onwatch",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '732-905-6951',
    email: 'ericapayseur@gmail.com',
    address: '170 Eva ct, Jackson, NJ 08257',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "John",
    mundaneLastName: "Simpson",
    scaFirstName: "Fenwick",
    scaLastName: "",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield", "combat-archery"],
    gearStatus: false,
    memberStatus: "onwatch",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '732-284-9102',
    email: '',
    address: '',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Micheal",
    mundaneLastName: "Guaracino",
    scaFirstName: "Tempo",
    scaLastName: "",
    registeredName: true,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield"],
    gearStatus: false,
    memberStatus: "member",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: 'Lord',
    phoneNumber: '856-882-8908',
    email: 'mguaracino@gmail.com',
    address: '6280 Polo Dr, Cummings, GA 30040',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Kordian",
    mundaneLastName: "Starczyk",
    scaFirstName: "Thaddeus",
    scaLastName: "",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield", "two-weapon"],
    gearStatus: false,
    memberStatus: "onwatch",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '201-647-5333',
    email: 'iam12bb@gmail.com',
    address: '510 Hamilton St, Sumerset, NJ ',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Corey",
    mundaneLastName: "Abernathy",
    scaFirstName: "Grimm",
    scaLastName: "idk",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield"],
    gearStatus: false,
    memberStatus: "member",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: 'Lord',
    phoneNumber: '609-433-0783',
    email: '',
    address: '',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Cory",
    mundaneLastName: "Walker",
    scaFirstName: "Sabine",
    scaLastName: "idk",
    registeredName: false,
    registeredArms: false,
    singlesFighter: false,
    combatArcher: false,
    meleeFighter: false,
    authorizedForms: [],
    gearStatus: false,
    memberStatus: "onwatch",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '423-368-8091',
    email: 'coryliana@gmail.com',
    address: '249 Broad St, Apt 311, Mattawan, NJ 07747',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Brandon",
    mundaneLastName: "Mickley",
    scaFirstName: "Jasper",
    scaLastName: "",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield"],
    gearStatus: false,
    memberStatus: "officer",
    admin: false,
    rank: "seneschal",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '908-907-4484',
    email: 'mcjasper1@live.com',
    address: '249 Broad St, Apt 311, Mattawan, NJ 07747',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Sam",
    mundaneLastName: "Arcaini",
    scaFirstName: "Malcom",
    scaLastName: "",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield"],
    gearStatus: false,
    memberStatus: "member",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '856-952-5953',
    email: '',
    address: '',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Joe",
    mundaneLastName: "Spagnoli",
    scaFirstName: "Liam",
    scaLastName: "idk",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["polearm"],
    gearStatus: false,
    memberStatus: "onwatch",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '732-662-0061',
    email: '',
    address: '',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Ed",
    mundaneLastName: "Had",
    scaFirstName: "Declan",
    scaLastName: "idk",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: ["sword&shield", "polearm", "spear", "two-weapon"],
    gearStatus: false,
    memberStatus: "officer",
    admin: false,
    rank: "Officer",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: 'Lord',
    phoneNumber: '845-642-9834',
    email: 'edwardhaddican@gmail.com',
    address: '4403 Nightfall ct., Durham, NC, 27713',
    memberId: '',
    authExpirationDate: '',
  },
  {
    mundaneFirstName: "Hunter",
    mundaneLastName: "Findon",
    scaFirstName: "Jeager",
    scaLastName: "",
    registeredName: false,
    registeredArms: false,
    singlesFighter: true,
    combatArcher: false,
    meleeFighter: true,
    authorizedForms: [],
    gearStatus: false,
    memberStatus: "prospect",
    admin: false,
    rank: "grunt",
    image: defaultImage,
    arms: defaultArms,
    notes: '',
    title: '',
    phoneNumber: '732-535-1179',
    email: 'hunterfindon@gmail.com',
    address: '437 Middletown-Lincroft rd, NJ',
    memberId: '',
    authExpirationDate: '',
  },
];






module.exports = userSeed;
